image: docker
services:
  - docker:dind
stages:
  - build_n_push_image
build_n_push_image:
  stage: build_n_push_image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image prune -f
    - apk add --no-cache docker-compose
    - docker-compose build --no-cache
    - docker push
      registry.gitlab.com/atomworks-io/jcb/jcb-lab-frontend:1.0.0.0-dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if:
        $CI_PIPELINE_SOURCE == "merge_request_event" &&
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "cr-1"
